# Generated by Django 2.2.5 on 2019-10-30 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('valor', models.BigIntegerField()),
                ('descripcion', models.CharField(default='', max_length=250)),
                ('especial', models.BooleanField(default=True)),
                ('enventa', models.BooleanField(default=True)),
                ('ingrediente', models.ManyToManyField(to='ingredientes.Ingrediente')),
            ],
        ),
    ]
