# Generated by Django 2.2.5 on 2019-11-12 01:33

from django.db import migrations

def CreaPizzas(apps, schema_editor):
	 pizza = apps.get_model('pizzas', 'pizza')
	 p1 = pizza(nombre = "Hawaiana", valor = 10, descripcion = "Tradicional")
	 p1.save()
	 pizza = apps.get_model('pizzas', 'pizza')
	 p2 = pizza(nombre = "Pollo y Champiñones", valor = 10, descripcion = "Tradicional")
	 p2.save()
	 pizza = apps.get_model('pizzas', 'pizza')
	 p3 = pizza(nombre = "Jamon y Queso", valor = 10, descripcion = "Tradicional")
	 p3.save()
	 
	 
	 ingrepizza = apps.get_model('pizzas', 'pizza_ingrediente')
	 ip1 = ingrepizza(pizza_id = 1, ingrediente_id = 1)
	 ip1.save()
	 ingrepizza = apps.get_model('pizzas', 'pizza_ingrediente')
	 ip2 = ingrepizza(pizza_id = 1, ingrediente_id = 2)
	 ip2.save()
	 ingrepizza = apps.get_model('pizzas', 'pizza_ingrediente')
	 ip3 = ingrepizza(pizza_id = 1, ingrediente_id = 3)
	 ip3.save()
	 
	 ingrepizza = apps.get_model('pizzas', 'pizza_ingrediente')
	 ip4 = ingrepizza(pizza_id = 2, ingrediente_id = 1)
	 ip4.save()
	 ingrepizza = apps.get_model('pizzas', 'pizza_ingrediente')
	 ip5 = ingrepizza(pizza_id = 2, ingrediente_id = 4)
	 ip5.save()
	 ingrepizza = apps.get_model('pizzas', 'pizza_ingrediente')
	 ip6 = ingrepizza(pizza_id = 2, ingrediente_id = 7)
	 ip6.save()
	 
	 ingrepizza = apps.get_model('pizzas', 'pizza_ingrediente')
	 ip7 = ingrepizza(pizza_id = 3, ingrediente_id = 1)
	 ip7.save()
	 ingrepizza = apps.get_model('pizzas', 'pizza_ingrediente')
	 ip8 = ingrepizza(pizza_id = 3, ingrediente_id = 3)
	 ip8.save()
	 
	 
class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0001_initial'),
    ]

    operations = [migrations.RunPython(CreaPizzas),
    ]
