# Generated by Django 2.2.5 on 2019-10-08 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredientes', '0001_initial'),
        ('pizzas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producto',
            new_name='Pizza',
        ),
    ]
