# Generated by Django 2.2.5 on 2019-11-23 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_auto_20191111_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='efectivo',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='estado_Factura',
        ),
        migrations.AddField(
            model_name='factura',
            name='ciudad',
            field=models.CharField(default='Cali', max_length=80),
        ),
    ]
