# Generated by Django 2.2.5 on 2019-11-30 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredientes', '0002_auto_20191111_1318'),
        ('pizzas', '0004_auto_20191125_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredientes_adicionales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('precio', models.FloatField()),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzas.Detalle')),
                ('ingredientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredientes.Ingrediente')),
            ],
        ),
    ]
