# Generated by Django 2.2.5 on 2019-11-30 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredientes', '0002_auto_20191111_1318'),
        ('pizzas', '0005_ingredientes_adicionales'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredientes_adicionales',
            new_name='IngredientesA',
        ),
    ]
