# Generated by Django 2.2.5 on 2019-11-06 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc', models.BigIntegerField()),
                ('telefono', models.BigIntegerField()),
                ('pais', models.CharField(max_length=50)),
                ('nombre_banco', models.CharField(max_length=50)),
                ('fecha_vencimiento', models.DateField(default=django.utils.timezone.now)),
                ('tipo_tarjeta', models.CharField(max_length=50)),
                ('numero_tarjeta', models.BigIntegerField()),
                ('cvv', models.IntegerField()),
                ('rol', models.CharField(choices=[('d', 'Digitador'), ('v', 'Vendedor'), ('a', 'Admin')], max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
