# Generated by Django 2.2.5 on 2019-10-07 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cc',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default='null@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='usuario',
            name='pais',
            field=models.CharField(default='Colombia', max_length=50),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.IntegerField(default=0),
        ),
    ]
