# Generated by Django 2.2.5 on 2019-11-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(blank=True, default='calle 13a 5e-01 Buga', max_length=200, null=True),
        ),
    ]
