# Generated by Django 2.2.5 on 2019-11-19 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20191117_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(blank=True, default='calle 100 100 av 100', max_length=200, null=True),
        ),
    ]
