# Generated by Django 2.2.5 on 2019-10-08 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20191007_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cvv',
            field=models.IntegerField(default=4562),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_vencimiento',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre_banco',
            field=models.CharField(default='bancolombia', max_length=50),
        ),
        migrations.AddField(
            model_name='usuario',
            name='numero_tarjeta',
            field=models.IntegerField(default=1546543214),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_tarjeta',
            field=models.CharField(default='master card', max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cc',
            field=models.BigIntegerField(default=1115087926),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.IntegerField(default=3154879521),
        ),
    ]
