# Generated by Django 2.2.5 on 2019-10-30 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20191028_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='numero_tarjeta',
            field=models.BigIntegerField(default=1115087926),
        ),
    ]
