# Generated by Django 2.2.5 on 2019-10-11 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20191007_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('d', 'Digitador'), ('v', 'Vendedor'), ('a', 'Admin')], max_length=1),
        ),
    ]
