# Generated by Django 2.2.5 on 2019-10-11 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20191010_2126'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Roles',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_vencimiento',
            field=models.DateField(),
        ),
    ]
