# Generated by Django 2.2.5 on 2019-10-11 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20191010_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_vencimiento',
            field=models.DateField(auto_now=True),
        ),
    ]
