# Generated by Django 2.2.5 on 2019-11-26 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franquicias', '0002_auto_20191104_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='franquicia',
            name='fecha_cancelada',
            field=models.DateField(blank=True, null=True),
        ),
    ]
